---
title: "June - C6-9"
output: html_document
date: "2023-03-16"
---
```{r setup , include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      fig.align = "center",
                      fig.width = 4, 
                      fig.height = 4, 
                      dev = "png",
                      cache = TRUE,
                      warning = FALSE, 
                      message = FALSE)
```


```{r library}
# Load packages

library(tidyverse)
library(stringr)
library(data.table)
library(janitor)
library(haven)
library(dplyr)
library(DT)
library(knitr)
```


```{r functions}


# Load functions

source("Functions/Functions.R")

```


```{r read}
# Datashare file path for import and export

Code_directory <-
  ("//s0177a/datashare/seerad/ags/census/branch1/NewStructure/Surveys/June/Codeconversion_2023")

# ADM schema for export

server <- "s0196a\\ADM"
database <- "RuralAndEnvironmentalScienceFarmingStatistics"
schema <- "juneagriculturalsurvey2023alpha"


allsaf_flagsorig <- loadRData(paste0(Code_directory, "/allsaf_B8flags.rda"))

censuspop<-read_sas("//s0177a/sasdata1/ags/census/agscens/address_occid_01JUN21.sas7bdat")

combined_data <- read.csv(paste0(Code_directory, "/COMBINED_DATA.csv"))

agscensprev<-read_sas("//s0177a/sasdata1/ags/census/agscens/june2020.sas7bdat")


allsaf_corrections <- loadRData(paste0(Code_directory, "/allsaf_B8corrections.rda"))
allsaf_permseas <- loadRData(paste0(Code_directory, "/allsaf_B8permseas.rda"))


allsaf_curr<-loadRData(paste0(Code_directory, "/allsaf_B8.rda"))


check_combined_dataSAS<-read.csv(paste0(Code_directory, "/CHECK_COMBINED_DATA.csv"))

compareSAS<-read.csv(paste0(Code_directory, "/COMPARE.csv"))

```



## This markdown doc outputs flagged records from the SAF dataset, flagged up in B8. It is based on C6-C9 of the SAS project.

```{r formatting, echo=FALSE}

censuspop<-as.data.frame(censuspop)

# Clean variable names

allsaf_flags<-clean_names(allsaf_flagsorig)
allsaf_flags$parish<-as.numeric(allsaf_flags$parish)
allsaf_flags$holding<-as.numeric(allsaf_flags$holding)
censuspop<-clean_names(censuspop)
censuspop$parish<-as.numeric(censuspop$parish)
censuspop$holding<-as.numeric(censuspop$holding)

allsaf_flags$flag<-" "

allsaf_flags<-allsaf_flags %>% 
  select (slc, fid, brn, mlc, field_area, landtype, claimtype, llo, code, area, parish, holding, flag1:flag4, flag) %>% 
  mutate(flag=
           ifelse( 
             flag1>0, paste(flag,"1"), flag),
         flag=
           ifelse( 
             flag2>0, paste(flag,"2"), flag),
         flag=
           ifelse( 
             flag4>0, paste(flag,"4"), flag),
         flag=
           ifelse( 
             flag5>0, paste(flag,"5"), flag),
         flag=
           ifelse( 
             flag6>0, paste(flag,"6"), flag),
         flag=
           ifelse( 
             flag7>0, paste(flag,"7"), flag),
         flag=
           ifelse( 
             flag8>0, paste(flag,"8"), flag),
         flag=
           ifelse( 
             flag9>0, paste(flag,"9"), flag))

# This created NAs so we have to remove them from flag here
         
allsaf_flags$flag<-gsub('\\D',' ',allsaf_flags$flag)

allsaf_flags$flag<-as.numeric(allsaf_flags$flag)

censuspop<-censuspop %>% 
  select(parish, holding, holding_classification_id, tot_area, tot_own_area)


flagged_holdings<-merge(allsaf_flags,censuspop, by=c("parish", "holding"))

flagged_holdings<-flagged_holdings %>% 
  mutate(
    population=
      ifelse(holding_classification_id==1|holding_classification_id==2|holding_classification_id==4|holding_classification_id==5|holding_classification_id==6|holding_classification_id==7|holding_classification_id==13,1,"")
  )


flagged_holdings<-flagged_holdings %>% 
  filter(population==1|flag6==1)

flagged_holdings<-flagged_holdings %>% 
  mutate(across(contains("flag"), ~ replace(., is.na(.), 0)))


flagged_fids<-flagged_holdings %>% 
  filter(rowSums(across(flag1:flag4))>0) %>% 
  select(fid)



fid_size<-allsaf_flags%>%  group_by(fid) %>% 
  select(fid, field_area) %>%
  summarise(max_field_area=max(field_area))

# Need to check these flagged records - SAS returns more


allsaf_flagged<-inner_join(allsaf_flags, flagged_fids, by="fid")


allsaf_flagged<-left_join(allsaf_flagged, fid_size, by="fid")
```


```{r results}

knitr::kable(allsaf_flagged)
```



```{r 3}
# Miscellaneous checks ----------------------------------------------------

# check that saf land areas are within +/- 100 ha of the total mp2 area

margin<-100



censuspopuse<-censuspop %>% 
  filter(holding_classification_id==1|holding_classification_id==2|holding_classification_id==4|holding_classification_id==5|holding_classification_id==6|holding_classification_id==7|holding_classification_id==13)

checksafareas<-left_join(combined_data,censuspopuse, by=c("parish","holding"))

checksafareas$parish <- str_pad(checksafareas$parish, width = 3, pad = "0")
checksafareas$holding <- str_pad(checksafareas$holding, width = 4, pad = "0")

checksafareas<-checksafareas %>% 
  select(parish, holding, item50, tot_area, land_data) %>% 
  filter(land_data=="saf"&item50>0&tot_area>0&(item50>tot_area+margin|item50<tot_area-margin)) %>% 
         mutate(slc=
                  paste0(parish, "/", holding, sep=""))

# Check areas previous year

# There's no variable called tot_area in the agscens dataset, so using item12 whichis total area of holding
# 


checksafareasprev<-agscensprev %>%
  select(parish, holding, item50,  item12, land_data) %>%
  filter(land_data=="saf"&item50>0&item12>0&(item50>item12+margin|item50<item12-margin)) %>%
  mutate(slc=
           paste0(parish, "/", holding, sep=""))
```


```{r flag7, echo=FALSE}
# Flag 7. This should be checked to make sure it only returns the first fid for each (distinct/unique)

flag7_fids<-flagged_holdings %>% 
  filter(flag7>0 & fid != 0) %>% 
  select (fid)

pfds_flag7<-inner_join(allsaf_flagged, flag7_fids, by="fid")
```


```{r flag7table, results='asis'}
kable(pfds_flag7)

```

```{r}


corrections_fid <- allsaf_corrections %>% group_by(fid) %>% 
  select(fid, field_area) %>%
  summarise(max_field_area=max(field_area))


allsaf_corrections<-inner_join(allsaf_corrections,corrections_fid,by="fid")


allsaf_after<-inner_join(allsaf_flagsorig,corrections_fid,by="fid")


allsaf_before<-inner_join(allsaf_permseas,corrections_fid,by="fid")

allsaf_corrections$amended<-"ERROR"
allsaf_before$amended<-"BEFORE"
allsaf_after$amended<-"AFTER"


allsaf_flagged<-rbind(allsaf_corrections,allsaf_before,allsaf_after)

allsaf_flagged$flag<-""

allsaf_flagged<-allsaf_flagged %>% 
mutate(flag=
         ifelse( 
           flag1>0, paste(flag,"1"), flag),
       flag=
         ifelse( 
           flag2>0, paste(flag,"2"), flag),
       flag=
         ifelse( 
           flag4>0, paste(flag,"4"), flag),
       flag=
         ifelse( 
           flag5>0, paste(flag,"5"), flag),
       flag=
         ifelse( 
           flag6>0, paste(flag,"6"), flag),
       flag=
         ifelse( 
           flag7>0, paste(flag,"7"), flag),
       flag=
         ifelse( 
           flag8>0, paste(flag,"8"), flag),
       flag=
         ifelse( 
           flag9>0, paste(flag,"9"), flag))
```

```{r, results='asis'}
# Output each fid in its own table

fids<-unique(allsaf_flagged$fid)

allsaf_flaggedtable<-allsaf_flagged %>% 
  select(line, amended, brn, slc, mlc, field_area, landtype, claimtype, LLO, code, area, flag,fid)

for (i in fids) {
  allsaf_flaggedsub<-subset(allsaf_flaggedtable, fid==i)
  
  print(kable(allsaf_flaggedsub, options=list(), caption=i))
  
}
```

```{r}
pfds_LLO_fids<-allsaf_curr %>% group_by(fid) %>% 
  filter(code=="LLO")

pfds_LLO_fids<-pfds_LLO_fids %>% 
  select(fid)

pfds_LLO<-left_join(pfds_LLO_fids,allsaf_curr,  by="fid")

pfds_LLO<-left_join(pfds_LLO, fid_size)
```


```{r, results='markup'}
# Output each LLO fid in its own table

LLOfids<-unique(pfds_LLO$fid)

LLOtable<-pfds_LLO %>% 
  select(line, brn, slc, mlc, field_area, landtype, claimtype, LLO, code, area,fid)

for (i in LLOfids) {
  LLO_sub<-subset(LLOtable, fid==i)
  
  print(datatable(LLO_sub, options=list(), caption=i))
  
}
```

```{r}

keyvars<-c("brn", "item7", "item11", "item12", "item46", "item47", "item48", "item49", "item50")

june20<-agscensprev %>% 
  select(parish, holding, all_of(keyvars)) %>% 
  mutate(diff20=
           item50-item12) %>% 
  rename_with(.fn = ~ paste0(.x, "_20"), .cols=keyvars)

censuspopuse2<-select(censuspop,-"holding_classification_id")

compare<-left_join(combined_data,june20, by=c("parish","holding"))
compare<-left_join(compare,censuspopuse2, by=c("parish","holding"))


compare<-compare %>% 
  mutate(
    item12=tot_area,
    item11 = tot_own_area,
    item7 = tot_area-tot_own_area,
    cropgrazing_change = (item46+item47-item46_20-item47_20), 
    woodland_change = item48_20-item48,
    othland_change = item49_20-item49,
    totland_change = item50_20-item50,
    mp2_change = item12_20-item12,
    diff = item12-item50
  )

compare$diff<-as.numeric(compare$diff)

check_combined_data<-compare %>% 
  mutate(
    item48_adj=item48,
    item49_adj=item49,
    item50_adj=item50,
    prop48=
      ifelse((item49_20+item49_20)>0,item48_20/(item49_20+item49_20) ,""),
    prop49=
      ifelse((item49_20+item49_20)>0,item49_20/(item49_20+item49_20) ,""),
    woodland_adj=
      ifelse(saf_data=="complete", pmin(woodland_change, diff),""),
    woodland_adj=
      ifelse(woodland_adj<0,0,woodland_adj),
    woodland_adj=as.numeric(woodland_adj),
    diff=
      ifelse(saf_data=="complete", (diff-woodland_adj),diff),
    othland_adj=
      ifelse(saf_data=="complete", pmin(othland_change, diff),""),
    othland_adj=
      ifelse(othland_adj<0,0,othland_adj),
    item48_adj=
      ifelse(saf_data=="complete", (item48+woodland_adj),item48),
    item49_adj=
      ifelse(saf_data=="complete", (item49+woodland_adj),item49),
    item50_adj=
      ifelse(saf_data=="complete", (item50+woodland_adj),item50),
    item48=item48_adj,
    item49=item49_adj,
    item50=item50_adj)
```


```{r, results='asis'}

diff_check<-compare %>% 
  filter(abs(diff)>100 & saf_data=="complete")

kable(diff_check)
```


```{r}
# Compare with SAS output

diff_checkSAS<-compareSAS %>% 
  filter(abs(diff)>100 & saf_data=="complete")


diff_checkSAS<-diff_checkSAS %>% 
  select(brn, item12, item50, diff)

```

