---
title: "JAC Punch Error Check (C1)"
date: "`r Sys.Date()`"
sgtemplates:
  datatables:
    features:
      info: true
      ordering: true
      paging: true
      searching: false
  header:
    phase_banner:
      tag: "WIP"
      text: "This is a work in progress."
    site_branding: "Scottish Government"
  metadata:
    label: "Report"
  navigation:
    toc:
      sticky: false
output:
  html_document:
    code_download: false
    df_print: paged
    fig_caption: true
    number_sections: false
    self_contained: false
    template: "_template.html"
    toc: true
    toc_depth: 2
    toc_float: false
---
```{r setup, include = FALSE } 
#yr = this year 20xx
yr <- 21
yr1 <- yr-1 
yr2 <-  yr-2
yr3 <-  yr-3

knitr::opts_chunk$set(echo = TRUE)



# Before import -----------------------------------------------------------


# Clear environment prior


# Datashare file path for import and export

Code_directory <-
  ("//s0177a/datashare/seerad/ags/census/branch1/NewStructure/Surveys/June/Codeconversion_2023")

# ADM schema for export

server <- "s0196a\\ADM"
database <- "RuralAndEnvironmentalScienceFarmingStatistics"
schema <- "juneagriculturalsurvey2023alpha"



###check if this has been updated for this year!!
source("./punch-error-checks_files/item categories.R")

#source("./punch-error-checks_files/punch error tables.R")

```


#JAC Survey form Punch Error Checks
The following table displays errors for holdings where:  total area has gone up or down by 10% and there has been an increase of grass greater than 5 years in the last year that does not account for the total of last year's rough grazings, fallow, other land and the difference in total land use area change.
```{r}

perr_finder <- function(x, dt){
  for (i in 1:nrow(dt)){if(x == 1){ print("Errors found")}
  else {print("No errors")} }
}
perr_finder(perr1, perr1)
```

